### ISSUE TITLE
The hard clip 'H' operator should not advance the query seq?

### ISSUE THREAD

**Issue by ddzhang3** [osthomas/sam_subseq#1]
Hi there, I'm confused with the strategy of query sequence extraction using CIGAR string. Mainly, my question is that,  the 'H' operator in CIGAR was used for query sequence advance as in the  code: https://github.com/osthomas/sam_subseq/blob/0870063e0d5edf4c42e131e45cf1861c0de10d8a/src/sam_subseq/IndexMap.py#L36 However, the hard clipping sequence is not presented in the SEQ field as far as I know. Thus 'H' should not be applied for query   sequence advance. 
Sorry if I misunderstood the corresponding codes

**Comment by ddzhang3** [comment]
I also notice these codes may be modified to `subseq = alignment[qry_start, qry_stop]`??
https://github.com/osthomas/sam_subseq/blob/0870063e0d5edf4c42e131e45cf1861c0de10d8a/src/sam_subseq/main.py#L101

**Comment by osthomas** [comment]
Hi, thank you for your comments!

> Mainly, my question is that, the 'H' operator in CIGAR was used for query sequence advance as in the code:
> 
> https://github.com/osthomas/sam_subseq/blob/0870063e0d5edf4c42e131e45cf1861c0de10d8a/src/sam_subseq/IndexMap.py#L36
> However, the hard clipping sequence is not presented in the SEQ field as far as I know. Thus 'H' should not be applied for query sequence advance.

`H` does not advance either query or reference:

https://github.com/osthomas/sam_subseq/blob/0870063e0d5edf4c42e131e45cf1861c0de10d8a/src/sam_subseq/IndexMap.py#L35

https://github.com/osthomas/sam_subseq/blob/0870063e0d5edf4c42e131e45cf1861c0de10d8a/src/sam_subseq/IndexMap.py#L215-L216

I see how this is confusingly written, though.




> I also notice these codes may be modified to `subseq = alignment[qry_start, qry_stop]`??
> 
> https://github.com/osthomas/sam_subseq/blob/0870063e0d5edf4c42e131e45cf1861c0de10d8a/src/sam_subseq/main.py#L101

Indexing the `SamRefAlignment` object is done with reference coordinates, they are converted to query coordinates internally.

https://github.com/osthomas/sam_subseq/blob/0870063e0d5edf4c42e131e45cf1861c0de10d8a/src/sam_subseq/SamRefAlignment.py#L37-L38

**Comment by ddzhang3** [comment]
> Hi, thank you for your comments!
> 
> > Mainly, my question is that, the 'H' operator in CIGAR was used for query sequence advance as in the code:
> > https://github.com/osthomas/sam_subseq/blob/0870063e0d5edf4c42e131e45cf1861c0de10d8a/src/sam_subseq/IndexMap.py#L36
> > 
> > However, the hard clipping sequence is not presented in the SEQ field as far as I know. Thus 'H' should not be applied for query sequence advance.
> 
> `H` does not advance either query or reference:
> 
> https://github.com/osthomas/sam_subseq/blob/0870063e0d5edf4c42e131e45cf1861c0de10d8a/src/sam_subseq/IndexMap.py#L35
> 
> https://github.com/osthomas/sam_subseq/blob/0870063e0d5edf4c42e131e45cf1861c0de10d8a/src/sam_subseq/IndexMap.py#L215-L216
> 
However, if I do not misunderstand the logic, the `is_clip` is assigned priorly outside of the `if else` statement and is not modified thereafter, which may lead to advance the query sequence at line 212
https://github.com/osthomas/sam_subseq/blob/0870063e0d5edf4c42e131e45cf1861c0de10d8a/src/sam_subseq/IndexMap.py#L208-L212
> I see how this is confusingly written, though.
> 
> > I also notice these codes may be modified to `subseq = alignment[qry_start, qry_stop]`??
> > https://github.com/osthomas/sam_subseq/blob/0870063e0d5edf4c42e131e45cf1861c0de10d8a/src/sam_subseq/main.py#L101
> 
> Indexing the `SamRefAlignment` object is done with reference coordinates, they are converted to query coordinates internally.
> 
> https://github.com/osthomas/sam_subseq/blob/0870063e0d5edf4c42e131e45cf1861c0de10d8a/src/sam_subseq/SamRefAlignment.py#L37-L38
Oh yes, I see now.

**Comment by osthomas** [comment]
> However, if I do not misunderstand the logic, the `is_clip` is assigned priorly outside of the `if else` statement and is not modified thereafter, which may lead to advance the query sequence at line 212

L. 212 is not reached for a `H` clip operation because this is `False`:

https://github.com/osthomas/sam_subseq/blob/0870063e0d5edf4c42e131e45cf1861c0de10d8a/src/sam_subseq/IndexMap.py#L211

It is only executed for an `S` clip.

**Comment by ddzhang3** [comment]
> > However, if I do not misunderstand the logic, the `is_clip` is assigned priorly outside of the `if else` statement and is not modified thereafter, which may lead to advance the query sequence at line 212
> 
> L. 212 is not reached for a `H` clip operation because this is `False`:
> 
> https://github.com/osthomas/sam_subseq/blob/0870063e0d5edf4c42e131e45cf1861c0de10d8a/src/sam_subseq/IndexMap.py#L211
> 
> It is only executed for an `S` clip.

You're right ^_^, I made an obvious mistake.
